name: Scan -> KI -> Order (5 min)

on:
  schedule:
    - cron: "*/5 * * * *"   # alle 5 Minuten (UTC) – läuft rund um die Uhr
  workflow_dispatch: {}      # manueller Start möglich

jobs:
  run-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show files
        run: |
          pwd
          ls -la
          echo "--- tickers.txt ---"
          test -f tickers.txt && cat tickers.txt || echo "tickers.txt fehlt!"

      - name: Restore state cache
        uses: actions/cache@v4
        with:
          path: state
          key: state-${{ runner.os }}-${{ github.ref_name }}-${{ github.run_id }}
          restore-keys: |
            state-${{ runner.os }}-${{ github.ref_name }}-
            state-${{ runner.os }}-

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure env
        run: |
          echo "KI_MODE=webhook" >> $GITHUB_ENV
          echo "TIMEFRAME=${{ vars.TIMEFRAME }}" >> $GITHUB_ENV
          echo "POSITION_QTY=${{ vars.POSITION_QTY }}" >> $GITHUB_ENV
          echo "RSI_LEN=${{ vars.RSI_LEN }}" >> $GITHUB_ENV
          echo "EMA_FAST=${{ vars.EMA_FAST }}" >> $GITHUB_ENV
          echo "EMA_SLOW=${{ vars.EMA_SLOW }}" >> $GITHUB_ENV
          echo "RSI_BUY_CROSS=${{ vars.RSI_BUY_CROSS }}" >> $GITHUB_ENV
          echo "RSI_SELL_CROSS=${{ vars.RSI_SELL_CROSS }}" >> $GITHUB_ENV
          echo "COOLDOWN_MIN=${{ vars.COOLDOWN_MIN }}" >> $GITHUB_ENV
          # Secrets
          echo "KI_WEBHOOK_URL=${{ secrets.KI_WEBHOOK_URL }}" >> $GITHUB_ENV
          echo "TP_WEBHOOK_URL=${{ secrets.TP_WEBHOOK_URL }}" >> $GITHUB_ENV

      - name: Run bot (unbuffered)
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          python -V
          echo ">>> Starting main.py …"
          python main.py

      - name: Save state cache (after run)
        if: always()
        uses: actions/cache@v4
        with:
          path: state
          key: state-${{ runner.os }}-${{ github.ref_name }}-${{ github.run_id }}

# Tipp: Nur während US-Handelszeiten laufen lassen (spart Minuten):
# on:
#   schedule:
#     - cron: "*/5 13-20 * * 1-5"   # Mo–Fr 13–20 UTC (Sommerzeit grob RTH)
#   workflow_dispatch: {}
